server:
  port: 18080
# redis 信息
spring:  redis:    database: 0
    password:
    port: 6379
    host: 127.0.0.1
    lettuce:      pool:        max-idle: 10
        max-wait: 1ms
        max-active: 10
        min-idle: 5
      shutdown-timeout: 100ms